作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔array3 = np.array([[4,5,6],[1,2,3]])


In [39]:
#. 將下兩列array存成npz檔\
import numpy as np
from io import StringIO

array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('multi_array.npz', 'wb') as f:
    np.savez(f ,arr1 = array1, arr2 = array2)

In [57]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6],[1,2,3]])

with open('multi_array.npz', 'wb') as f:
    np.savez(f ,arr1 = array1, arr2 = array2, arr3 = array3)
    
f = np.load("multi_array.npz")
print(f['arr1'],"\n")
print(f['arr2'],"\n")
print(f['arr3'],"\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[2 3 5] 

[[4 5 6]
 [1 2 3]] 

